### PR TITLE
Update oEmbed Attributes for Player

### PR DESCRIPTION
**Pull request by iuriandreazza**
Hey there, this is a simple addition to props to match the spec of the player.js embed options.

### CODE REVIEW

**Comment by iuriandreazza** [comment]
@goto-bus-stop could you review this, if it's ok merge ? :) please let me know if you want to change in the PR

**Comment by jdpnielsen** [comment]
I would love for this to be merged and released :pray:

**Comment by goto-bus-stop** [comment]
I guess we should add the props for this but as far as I can tell most of the `player.setXYZ()` methods this PR uses do not actually exist. They would have to use the appropriate methods instead, or not support changes at all if they can't be changed with the vimeo API.

**Review by ArturBarbosa — APPROVED** [review]

**Comment by goto-bus-stop** [comment]
Sorry I left this for so long. the props this PR adds have been implemented in other changes in the mean time, so it's now obsolete I think. thanks for the contribution! 🥰

**Pull request closed without merging**
