### PR TITLE
Add support for passing the 'dnt' player param as a prop

### PR DESCRIPTION
**Pull request by k-p-jones**
This PR adds support for passing the `dnt` prop to disable cookies and tracking.

https://github.com/u-wave/react-vimeo/issues/121

### CODE REVIEW

**Review by goto-bus-stop — APPROVED** [review]
thank you!

**Comment by k-p-jones** [comment]
No problem :)

**Comment by rburgstaller** [comment]
looks like the parameter is not visible in the typescript defs

**Comment by k-p-jones** [comment]
I've submitted a PR to address that, thanks for pointing it out

**Pull request merged**
